
### LEER PUNTUACIONES
GET http://localhost:3000/puntuaciones


### CREAR PUNTUACIÓN USUARIO
POST http://localhost:3000/puntuaciones
Content-Type: application/json

{
    "nombre": "Fulanita",
    "dificultad": "Intermedio",
    "puntuacion": "5000"
}
