@url = cluster0.mdf0qyj.mongodb.net

### LEER PUNTUACIONES
GET http://localhost:3000/puntuaciones


### CREAR PUNTUACIÓN USUARIO
POST http://localhost:3000/puntuaciones
Content-Type: application/json

{
    "nombre": "Menganito",
    "dificultad": "Difícil",
    "puntuacion": "7731"
}
